---
- hosts: all
  remote_user: ubuntu
  gather_facts: no
  vars_files:
    - vars/default.yml
  tasks:
    - name: Set Hostname
      become: yes
      hostname:
        name: "{{ inventory_hostname }}"

    - name: edit /etc/hosts
      become: yes
      ansible.builtin.replace:
        path: /etc/hosts
        regexp: '(\s+)old\.host\.name(\s+.*)?$'
        replace: '\1new.host.name\2'
   ################ Working chanch name second variant
  # - hosts: all
  #   become: true
  #   tasks:
  #     - name: Set a hostname
  #       ansible.builtin.hostname:
  #         name: wordpress

  #     - name: Set a hostname specifying strategy
  #       ansible.builtin.hostname:
  #         name: wordpress
  #         use: systemd